name: CMake

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Workflow Approval

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      working-directory: ${{github.workspace}}
      run: echo yes | .github/workflows/install-requirements.sh

    - name: Format
      run: |
        pre-commit install
        pre-commit run --all-files

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j

    - name: Install
      run: cmake --install ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build/bin
      run: ./test_harness --backend_lib_path ../lib/libhebench_example_backend.so

    - name: Validation
      working-directory: ${{github.workspace}}/build
      run: ../.github/workflows/validate_testharness_output.sh
